#!/usr/bin/env node
/*
 * Build-time generator for boiseparks.com. Produces:
 *   js/parks-data.js        — window.BOISE_PARKS bundle (parks.json merged with tips.json)
 *   parks/<slug>/index.html — static SEO page per park with schema.org Park JSON-LD
 *   sitemap.xml             — homepage + every park page, lastmod = today
 * Data pipeline that creates data/parks.json lives in scripts/fetch-data.py.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://boiseparks.com';
const parks = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/parks.json'), 'utf8'));
const tips = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/tips.json'), 'utf8'));
const parking = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/parking.json'), 'utf8'));

for (const p of parks) {
  if (tips[p.slug]) p.tip = tips[p.slug];
  if (parking[p.slug]) p.parking = parking[p.slug];
}

// ---------- Parent Score: transparent 0–10, computed only from the amenity data ----------
function parentScore(p) {
  const bits = [];
  let s = 0, v = 0;
  v = 0;
  if (p.playground) {
    v = 1.5;
    if (p.playground.toddler && p.playground.bigKid) v += 0.5;   // both age ranges
    if (p.playground.rubberSurface || p.playground.ada) v += 0.5; // accessible surfacing
    if (p.playground.newestYear >= 2015) v += 0.5;                // recently updated
  }
  s += v; bits.push(['Playground', v, 3]);
  v = { 'year-round': 2, 'seasonal+portable': 1.5, 'seasonal': 1, 'none': 0 }[p.restroom];
  s += v; bits.push(['Restrooms', v, 2]);
  v = { leafy: 1.5, some: 0.75, 'full-sun': 0 }[p.shade];
  s += v; bits.push(['Shade', v, 1.5]);
  v = (p.water || p.pool) ? 1 : 0;
  s += v; bits.push(['Water play', v, 1]);
  v = (p.shelter || p.reservable) ? 0.5 : 0;
  s += v; bits.push(['Picnic shelter', v, 0.5]);
  v = p.parking ? { lot: 1, downtown: 0.5, street: 0 }[p.parking.type] : 0;
  s += v; bits.push(['Easy parking', v, 1]);
  v = Math.min(1, 0.25 * ((p.greenbelt ? 1 : 0) + (p.fishing ? 1 : 0) + (p.openPlay ? 1 : 0) +
      ((p.courts.length || p.fields.length) ? 1 : 0) + (p.extras.length ? 1 : 0)));
  s += v; bits.push(['Extras (Greenbelt, fishing, courts…)', v, 1]);
  p.score = Math.round(s * 10) / 10;
  p.scoreBits = bits;
}
parks.forEach(parentScore);

// ---------- js/parks-data.js ----------
fs.mkdirSync(path.join(ROOT, 'js'), { recursive: true });
fs.writeFileSync(
  path.join(ROOT, 'js/parks-data.js'),
  '// Generated by scripts/gen.js — do not edit by hand. Source: data/parks.json + data/tips.json\n' +
  'window.BOISE_PARKS = ' + JSON.stringify(parks) + ';\n'
);

// ---------- helpers ----------
const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const cap = s => s.charAt(0).toUpperCase() + s.slice(1);

const RESTROOM_LABEL = {
  'year-round': 'Heated restrooms, open year-round',
  'seasonal+portable': 'Seasonal restrooms; portable toilet in winter',
  'seasonal': 'Seasonal restrooms (closed in winter)',
  'none': 'No restrooms at this park',
};
const SHADE_LABEL = { 'leafy': 'Leafy — lots of mature tree cover', 'some': 'Some shade — a mix of trees and open lawn', 'full-sun': 'Mostly full sun — pack hats and sunscreen' };
const PARKING_LABEL = { lot: 'Dedicated parking lot', street: 'Street parking — no dedicated lot', downtown: 'Metered street parking & paid garages nearby' };
const parkingText = p => p.parking ? (p.parking.note || PARKING_LABEL[p.parking.type]) : null;
const scoreClasses = s => s >= 8 ? 'bg-meadow text-white' : s >= 6 ? 'bg-meadow-light text-meadow-deep' : s >= 4 ? 'bg-sun-light text-sun' : 'bg-stone-100 text-bark';
const fmtScore = s => (s % 1 === 0 ? s.toFixed(0) : s.toFixed(1));

function directionsUrl(p) {
  return 'https://www.google.com/maps/dir/?api=1&destination=' + encodeURIComponent(`${p.name}, ${p.address}, Boise, ID ${p.zip}`);
}

function playgroundBits(p) {
  const pg = p.playground;
  if (!pg) return null;
  const ages = pg.toddler && pg.bigKid ? 'toddlers (2–5) and big kids (5–12)' : pg.toddler ? 'toddlers (2–5)' : pg.bigKid ? 'big kids (5–12)' : null;
  const bits = [];
  if (ages) bits.push(`Equipment for ${ages}`);
  if (pg.features.length) bits.push(cap(pg.features.join(', ')));
  if (pg.surface) bits.push(`${cap(pg.surface)} surfacing${pg.rubberSurface ? ' (stroller & wheelchair friendly)' : ''}`);
  if (pg.ada) bits.push('ADA-accessible equipment');
  if (pg.newestYear) bits.push(`Newest structure installed ${pg.newestYear}`);
  return bits;
}

// ---------- park pages ----------
const header = `
<header class="sticky top-0 z-40 border-b border-meadow/15 bg-cream/90 backdrop-blur">
  <div class="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3">
    <a href="/" class="flex items-center gap-2.5">
      <img src="/favicon.svg" alt="" class="h-8 w-8">
      <span class="font-display text-lg font-bold text-meadow-deep">boise<span class="text-meadow">parks</span>.com</span>
    </a>
    <nav class="flex items-center gap-4 text-sm font-medium text-bark">
      <a href="/#map" class="hover:text-meadow-deep">Map</a>
      <a href="/#best-of" class="hidden sm:block hover:text-meadow-deep">Best of</a>
      <a href="/#faq" class="hidden sm:block hover:text-meadow-deep">FAQ</a>
      <a href="/#parks" class="rounded-full bg-meadow px-3.5 py-1.5 text-white hover:bg-meadow-dark">All parks</a>
    </nav>
  </div>
</header>`;

const footer = `
<footer class="mt-16 border-t border-meadow/15 bg-meadow-deep py-10 text-sm text-white/80">
  <div class="mx-auto max-w-6xl px-4">
    <div class="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
      <div class="max-w-md">
        <p class="font-display text-base font-bold text-white">boiseparks.com</p>
        <p class="mt-2">The parent's guide to every park in Boise — playgrounds, splash pads, restrooms, shade and more, built from official City of Boise data.</p>
      </div>
      <div class="text-white/70">
        <p>Park data: <a class="underline hover:text-white" href="https://opendata.cityofboise.org/" rel="noopener">City of Boise Open Data</a> &amp; <a class="underline hover:text-white" href="https://www.cityofboise.org/departments/parks-and-recreation/" rel="noopener">Boise Parks and Recreation</a>.</p>
        <p class="mt-1">Not affiliated with the City of Boise. Details can change — check the city page before you count on a specific amenity.</p>
      </div>
    </div>
  </div>
</footer>`;

const pgDir = path.join(ROOT, 'parks');
fs.rmSync(pgDir, { recursive: true, force: true });

for (const p of parks) {
  const url = `${SITE}/parks/${p.slug}/`;
  const pgBits = playgroundBits(p);
  const title = `${p.name} — Playground, Restrooms & Amenities | Boise Parks`;
  const descText = p.tip || p.desc || `${p.name} in Boise, Idaho: amenities, playground details, restrooms and more.`;
  const metaDesc = esc(descText.replace(/\s+/g, ' ').slice(0, 158));

  const amenities = [];
  if (p.playground) amenities.push('Playground');
  if (p.water) amenities.push(p.water.type);
  if (p.pool) amenities.push('Outdoor pool');
  if (p.restroom !== 'none') amenities.push('Restrooms');
  if (p.shelter) amenities.push('Picnic shelter');
  if (p.greenbelt) amenities.push('Greenbelt access');
  if (p.fishing) amenities.push('Fishing');
  if (p.dogPark) amenities.push('Dog off-leash area');
  if (p.openPlay) amenities.push('Open play areas');
  amenities.push(...p.courts.map(cap), ...p.fields.map(cap), ...p.extras.map(cap));

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Park',
    name: p.name,
    url,
    address: { '@type': 'PostalAddress', streetAddress: p.address, addressLocality: 'Boise', addressRegion: 'ID', postalCode: p.zip, addressCountry: 'US' },
    geo: { '@type': 'GeoCoordinates', latitude: p.lat, longitude: p.lon },
    description: descText.replace(/\s+/g, ' ').slice(0, 300),
    amenityFeature: amenities.map(a => ({ '@type': 'LocationFeatureSpecification', name: a, value: true })),
    isAccessibleForFree: true,
    ...(p.img ? { image: p.img } : {}),
  };
  const breadcrumb = {
    '@context': 'https://schema.org', '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Boise Parks', item: SITE + '/' },
      { '@type': 'ListItem', position: 2, name: p.name, item: url },
    ],
  };

  const factRows = [
    ['Size', `${p.acres} acres`],
    ['Area', p.area],
    ['Type', p.type + ' park'],
    ['Address', `${p.address}, Boise, ID ${p.zip}`],
    ['Restrooms', RESTROOM_LABEL[p.restroom]],
    ...(p.parking ? [['Parking', parkingText(p)]] : []),
    ['Shade', SHADE_LABEL[p.shade] + (p.trees ? ` (${p.trees.toLocaleString()} park trees in the city inventory)` : '')],
  ];
  if (p.water) factRows.push(['Water play', `${p.water.type} — ${p.water.hours}`]);
  if (p.reservable) factRows.push(['Reservations', 'Picnic shelter/area reservable through the city']);

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)}</title>
  <meta name="description" content="${metaDesc}">
  <link rel="canonical" href="${url}">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${metaDesc}">
  <meta property="og:type" content="place">
  <meta property="og:url" content="${url}">
  ${p.img ? `<meta property="og:image" content="${esc(p.img)}">` : ''}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600..800&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/styles.css">
  <script type="application/ld+json">${JSON.stringify(schema)}</script>
  <script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>
</head>
<body class="bg-cream font-sans text-ink">
${header}
<main class="mx-auto max-w-4xl px-4 pb-8 pt-8">
  <nav class="text-[13px] text-bark" aria-label="Breadcrumb"><a href="/" class="hover:text-meadow-deep">Boise Parks</a> <span class="mx-1 text-bark/50">/</span> <span class="font-medium text-meadow-deep">${esc(p.name)}</span></nav>
  <h1 class="mt-3 font-display text-3xl font-bold text-meadow-deep sm:text-4xl">${esc(p.name)}</h1>
  <p class="mt-1.5 text-[15px] text-bark">${esc(p.address)}, Boise, ID ${esc(p.zip)} · ${p.acres} acres · ${esc(p.area)}</p>

  ${p.img ? `<img src="${esc(p.img)}" alt="${esc(p.name)} in Boise, Idaho" class="mt-6 aspect-[16/8] w-full rounded-2xl object-cover shadow-card" loading="lazy" onerror="this.remove()">` : ''}

  ${p.tip ? `<div class="mt-6 rounded-2xl border border-sun/40 bg-sun-light px-5 py-4"><p class="text-[13px] font-bold uppercase tracking-wide text-sun">Parent notes</p><p class="mt-1.5 text-[15px] leading-relaxed">${esc(p.tip)}</p></div>` : ''}

  <div class="mt-8 grid gap-8 sm:grid-cols-5">
    <div class="sm:col-span-3">
      <h2 class="font-display text-xl font-bold text-meadow-deep">The essentials</h2>
      <dl class="mt-3 divide-y divide-meadow/10 rounded-2xl border border-meadow/15 bg-white px-5 shadow-card">
        ${factRows.map(([k, v]) => `<div class="flex gap-4 py-3 text-[14.5px]"><dt class="w-28 shrink-0 font-semibold text-meadow-deep">${esc(k)}</dt><dd class="text-ink/90">${esc(v)}</dd></div>`).join('\n        ')}
      </dl>
      ${pgBits ? `
      <h2 class="mt-8 font-display text-xl font-bold text-meadow-deep">Playground</h2>
      <ul class="mt-3 space-y-2 rounded-2xl border border-meadow/15 bg-white px-5 py-4 text-[14.5px] shadow-card">
        ${pgBits.map(b => `<li class="flex gap-2"><span class="text-meadow">✓</span> ${esc(b)}</li>`).join('\n        ')}
      </ul>` : `<p class="mt-8 rounded-2xl border border-meadow/15 bg-white px-5 py-4 text-[14.5px] text-bark shadow-card">No playground at this park.</p>`}
      ${p.desc ? `
      <h2 class="mt-8 font-display text-xl font-bold text-meadow-deep">About ${esc(p.name)}</h2>
      <p class="mt-3 text-[15px] leading-relaxed text-ink/90">${esc(p.desc)}</p>
      <p class="mt-2 text-[13px] text-bark">Description from <a href="${esc(p.cityUrl || 'https://www.cityofboise.org/departments/parks-and-recreation/parks/')}" class="underline hover:text-meadow-deep" rel="noopener">Boise Parks and Recreation</a>.</p>` : ''}
    </div>
    <aside class="sm:col-span-2">
      <div class="mb-4 rounded-2xl border border-meadow/15 bg-white p-5 shadow-card">
        <div class="flex items-center justify-between gap-3">
          <h2 class="font-display text-lg font-bold text-meadow-deep">Parent Score</h2>
          <span class="rounded-xl px-2.5 py-1 text-lg font-bold ${scoreClasses(p.score)}">${fmtScore(p.score)}<span class="text-[12px] font-semibold opacity-70">/10</span></span>
        </div>
        <ul class="mt-3 space-y-1.5 text-[13px] text-ink/85">
          ${p.scoreBits.map(([label, v, max]) => `<li class="flex items-baseline justify-between gap-2"><span>${esc(label)}</span><span class="font-semibold ${v === 0 ? 'text-bark/50' : 'text-meadow-deep'}">${fmtScore(v)}<span class="font-normal text-bark/60">/${fmtScore(max)}</span></span></li>`).join('\n          ')}
        </ul>
        <p class="mt-3 text-[12px] leading-snug text-bark">How easy a visit is with kids, computed from the amenity data — <a href="/#about" class="underline">methodology</a>.</p>
        <div class="mt-3 border-t border-meadow/10 pt-3">
          <p class="text-[13px] font-semibold text-meadow-deep">Your rating</p>
          <div class="bp-stars mt-1 text-2xl leading-none" data-slug="${p.slug}" role="radiogroup" aria-label="Your rating"></div>
          <p class="mt-1 text-[11.5px] text-bark">Tap to rate (tap again to clear) — saved on this device.</p>
        </div>
      </div>
      <div class="rounded-2xl border border-meadow/15 bg-white p-5 shadow-card">
        <h2 class="font-display text-lg font-bold text-meadow-deep">Everything here</h2>
        <ul class="mt-3 flex flex-wrap gap-1.5 text-[12.5px] font-medium">
          ${amenities.map(a => `<li class="rounded-md bg-meadow-light px-2 py-1 text-meadow-deep">${esc(a)}</li>`).join('\n          ')}
        </ul>
        <div class="mt-5 grid gap-2">
          <a href="/?park=${p.slug}#map" class="rounded-xl bg-meadow px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-meadow-dark">See on the map</a>
          <a href="${directionsUrl(p)}" rel="noopener" class="rounded-xl border border-meadow/30 bg-white px-4 py-2.5 text-center text-sm font-semibold text-meadow-deep hover:bg-meadow-light">Get directions</a>
          ${p.cityUrl ? `<a href="${esc(p.cityUrl)}" rel="noopener" class="rounded-xl border border-meadow/30 bg-white px-4 py-2.5 text-center text-sm font-semibold text-meadow-deep hover:bg-meadow-light">Official city page</a>` : ''}
        </div>
      </div>
    </aside>
  </div>
</main>
${footer}
<script>
(function(){
  var KEY='bp-ratings';
  function load(){ try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return{}} }
  document.querySelectorAll('.bp-stars').forEach(function(el){
    var slug=el.dataset.slug;
    function draw(){
      var r=load()[slug]||0, h='';
      for(var i=1;i<=5;i++) h+='<button type="button" data-v="'+i+'" aria-label="'+i+' star'+(i>1?'s':'')+'" class="'+(i<=r?'text-sun':'text-bark/25')+' hover:scale-110" style="transition:transform .1s">★</button>';
      el.innerHTML=h;
    }
    el.addEventListener('click',function(e){
      var b=e.target.closest('[data-v]'); if(!b) return;
      var all=load(), v=+b.dataset.v;
      if(all[slug]===v) delete all[slug]; else all[slug]=v;
      localStorage.setItem(KEY,JSON.stringify(all)); draw();
    });
    draw();
  });
})();
</script>
</body>
</html>
`;
  const dir = path.join(pgDir, p.slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html);
}

// ---------- cache-bust the data bundle reference in index.html ----------
const idxPath = path.join(ROOT, 'index.html');
const stamp = Date.now().toString(36);
fs.writeFileSync(idxPath, fs.readFileSync(idxPath, 'utf8').replace(/js\/parks-data\.js\?v=[a-z0-9]+/, `js/parks-data.js?v=${stamp}`));

// ---------- sitemap ----------
const today = new Date().toISOString().slice(0, 10);
const urls = [`${SITE}/`, ...parks.map(p => `${SITE}/parks/${p.slug}/`)];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);

console.log(`✓ ${parks.length} park pages, js/parks-data.js, sitemap.xml`);
