#!/usr/bin/env node
/*
 * Build-time generator for boiseparks.com. Produces:
 *   js/parks-data.js        — window.BOISE_PARKS bundle (parks.json merged with tips.json)
 *   parks/<slug>/index.html — static SEO page per park with schema.org Park JSON-LD
 *   <guide>/index.html      — topic guide pages (see scripts/guides.js)
 *   sitemap.xml             — homepage + every park page + guides, lastmod = today
 * Data pipeline that creates data/parks.json lives in scripts/fetch-data.py.
 */
const fs = require('fs');
const path = require('path');
const buildGuides = require('./guides');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://boiseparks.com';

// Google Analytics 4 — single source of truth. Stamped into every park page's
// <head> below and into index.html (between the ga:start/ga:end markers).
const GA_ID = 'G-RE6TED2HBZ';
const gaSnippet =
`<!-- Google Analytics (GA4) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=${GA_ID}"></script>
  <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${GA_ID}');</script>`;
const parks = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/parks.json'), 'utf8'));
const tips = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/tips.json'), 'utf8'));
const parking = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/parking.json'), 'utf8'));
const photos = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/photos.json'), 'utf8'));

for (const p of parks) {
  if (tips[p.slug]) p.tip = tips[p.slug];
  if (parking[p.slug]) p.parking = parking[p.slug];
  // Use only openly-licensed Wikimedia Commons photos (data/photos.json); never
  // the City of Boise CDN images that used to live in p.img.
  delete p.img;
  if (photos[p.slug]) p.photo = photos[p.slug];
}

// ---------- Parent Score: transparent 0–10, computed only from the amenity data ----------
// Philosophy: what actually makes a park good for kids is the playground, tree
// cover, and open grass — plus restrooms. Those four are the CORE (max 9). Water
// features, shelters and trails are nice-to-haves, so they're small BONUSES that
// only ADD (capped at +1) and never drag a park down for lacking them. Parking is
// logistics, not park quality, so it's shown separately and left out of the score.
const round1 = n => Math.round(n * 10) / 10;
function parentScore(p) {
  const core = [];
  // Playground (max 3.5) — the #1 reason you take kids to a park
  let v = 0;
  if (p.playground) {
    v = 2;
    if (p.playground.toddler && p.playground.bigKid) v += 0.5;    // equipment for both age ranges
    if (p.playground.rubberSurface || p.playground.ada) v += 0.5; // accessible surfacing
    if (p.playground.newestYear >= 2015) v += 0.5;                // built or rebuilt recently
  }
  core.push(['Playground', v, 3.5]);
  // Tree cover / shade (max 2.5) — comfort on a Boise summer afternoon
  core.push(['Tree cover', { leafy: 2.5, some: 1.25, 'full-sun': 0 }[p.shade], 2.5]);
  // Open grass & room to run (max 1.5). The city's Open_Play_Areas flag misses
  // some obviously grassy parks (e.g. 148-acre Ann Morrison), so also count
  // grassy sports fields (soccer/football/softball/cricket/multi-use) as room to run.
  const hasGrass = p.openPlay || (p.fields && p.fields.length > 0);
  core.push(['Open grass & room to run', hasGrass ? 1.5 : 0, 1.5]);
  // Restrooms (max 1.5)
  core.push(['Restrooms', { 'year-round': 1.5, 'seasonal+portable': 1, 'seasonal': 0.75, 'none': 0 }[p.restroom], 1.5]);

  // Bonuses — presence only, capped at +1, never a penalty
  const bonusDefs = [
    ['Splash pad / water', (p.water || p.pool), 0.5],
    ['Picnic shelter', (p.shelter || p.reservable), 0.25],
    ['Greenbelt / trails', p.greenbelt, 0.25],
    ['Fishing', p.fishing, 0.25],
    ['Sport courts & fields', (p.courts.length || p.fields.length), 0.25],
  ];
  const earned = bonusDefs.filter(b => b[1]);
  const bonusRaw = earned.reduce((a, b) => a + b[2], 0);
  const bonus = Math.min(1, bonusRaw);

  const coreSum = core.reduce((a, b) => a + b[1], 0);
  p.score = round1(Math.min(10, coreSum + bonus));
  p.scoreRows = core.map(([label, got, max]) => ({ label, got, max }));
  p.bonus = { got: round1(bonus), items: earned.map(b => b[0]) };
}
parks.forEach(parentScore);

// The raw City of Boise Park_Description is kept in data/parks.json only as
// source material for writing/verifying our own notes. It is never published:
// strip it here so no verbatim city text ships in the bundle or on any page.
parks.forEach(p => { delete p.desc; });

// ---------- js/parks-data.js ----------
fs.mkdirSync(path.join(ROOT, 'js'), { recursive: true });
fs.writeFileSync(
  path.join(ROOT, 'js/parks-data.js'),
  '// Generated by scripts/gen.js — do not edit by hand. Source: data/parks.json + data/tips.json\n' +
  'window.BOISE_PARKS = ' + JSON.stringify(parks) + ';\n'
);

// ---------- helpers ----------
const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const cap = s => s.charAt(0).toUpperCase() + s.slice(1);

const RESTROOM_LABEL = {
  'year-round': 'Heated restrooms, open year-round',
  'seasonal+portable': 'Seasonal restrooms; portable toilet in winter',
  'seasonal': 'Seasonal restrooms (closed in winter)',
  'none': 'No restrooms at this park',
};
const SHADE_LABEL = { 'leafy': 'Leafy — lots of mature tree cover', 'some': 'Some shade — a mix of trees and open lawn', 'full-sun': 'Mostly full sun — pack hats and sunscreen' };
const PARKING_LABEL = { lot: 'Dedicated parking lot', street: 'On-street parking', downtown: 'Metered street parking & paid garages nearby' };
const parkingText = p => p.parking ? (p.parking.note || PARKING_LABEL[p.parking.type]) : null;
const scoreClasses = s => s >= 8 ? 'bg-meadow text-white' : s >= 6 ? 'bg-meadow-light text-meadow-deep' : s >= 4 ? 'bg-sun-light text-sun' : 'bg-stone-100 text-bark';
const fmtScore = s => (s % 1 === 0 ? s.toFixed(0) : s.toFixed(1));

// Google Maps place link (shows the park's location, not directions).
function mapsUrl(p) {
  return 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(`${p.name}, ${p.address}, Boise, ID ${p.zip}`);
}

function playgroundBits(p) {
  const pg = p.playground;
  if (!pg) return null;
  const ages = pg.toddler && pg.bigKid ? 'toddlers (2–5) and big kids (5–12)' : pg.toddler ? 'toddlers (2–5)' : pg.bigKid ? 'big kids (5–12)' : null;
  const bits = [];
  if (ages) bits.push(`Equipment for ${ages}`);
  if (pg.features.length) bits.push(cap(pg.features.join(', ')));
  if (pg.surface) bits.push(`${cap(pg.surface)} surfacing${pg.rubberSurface ? ' (stroller & wheelchair friendly)' : ''}`);
  if (pg.ada) bits.push('ADA-accessible equipment');
  if (pg.newestYear) bits.push(`Newest structure installed ${pg.newestYear}`);
  return bits;
}

// ---------- park pages ----------
const header = `
<header class="sticky top-0 z-40 border-b border-meadow/15 bg-cream/90 backdrop-blur">
  <div class="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3">
    <a href="/" class="flex items-center gap-2.5">
      <img src="/favicon.svg" alt="" class="h-8 w-8">
      <span class="font-display text-lg font-bold text-meadow-deep">boise<span class="text-meadow">parks</span>.com</span>
    </a>
    <nav class="flex items-center gap-3 text-[13px] font-medium text-bark sm:gap-5 sm:text-sm">
      <a href="/best-playgrounds/" class="hidden xs:inline hover:text-meadow-deep">Playgrounds</a>
      <a href="/splash-pads/" class="hover:text-meadow-deep">Splash pads</a>
      <a href="/#map" class="hover:text-meadow-deep">Map</a>
      <a href="/#parks" class="whitespace-nowrap rounded-full bg-meadow px-3 py-1.5 text-white hover:bg-meadow-dark sm:px-3.5">All parks</a>
    </nav>
  </div>
</header>`;

const footer = `
<footer class="mt-16 border-t border-meadow/15 bg-meadow-deep py-10 text-sm text-white/80">
  <div class="mx-auto max-w-6xl px-4">
    <div class="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
      <div class="max-w-md">
        <p class="font-display text-base font-bold text-white">boiseparks.com</p>
        <p class="mt-2">The parent's guide to every park in Boise — playgrounds, splash pads, restrooms, shade and more, built from official City of Boise data.</p>
        <ul class="mt-4 flex flex-wrap gap-x-4 gap-y-1.5 font-medium text-white">
          <li><a class="underline decoration-white/40 underline-offset-2 hover:decoration-white" href="/best-playgrounds/">Best playgrounds</a></li>
          <li><a class="underline decoration-white/40 underline-offset-2 hover:decoration-white" href="/splash-pads/">Splash pads</a></li>
          <li><a class="underline decoration-white/40 underline-offset-2 hover:decoration-white" href="/restrooms/">Park restrooms</a></li>
        </ul>
      </div>
      <div class="text-white/70">
        <p>Park data: <a class="underline hover:text-white" href="https://opendata.cityofboise.org/" rel="noopener">City of Boise Open Data</a> &amp; <a class="underline hover:text-white" href="https://www.cityofboise.org/departments/parks-and-recreation/" rel="noopener">Boise Parks and Recreation</a>.</p>
        <p class="mt-1">Not affiliated with the City of Boise. Details can change — check the city page before you count on a specific amenity.</p>
      </div>
    </div>
  </div>
</footer>`;

const pgDir = path.join(ROOT, 'parks');
fs.rmSync(pgDir, { recursive: true, force: true });

for (const p of parks) {
  const url = `${SITE}/parks/${p.slug}/`;
  const pgBits = playgroundBits(p);
  const title = `${p.name} — Playground, Restrooms & Amenities | Boise Parks`;
  const descText = p.tip || `${p.name} in Boise, Idaho: amenities, playground details, restrooms and more.`;
  const metaDesc = esc(descText.replace(/\s+/g, ' ').slice(0, 158));

  const amenities = [];
  if (p.playground) amenities.push('Playground');
  if (p.water) amenities.push(p.water.type);
  if (p.pool) amenities.push('Outdoor pool');
  if (p.restroom !== 'none') amenities.push('Restrooms');
  if (p.shelter) amenities.push('Picnic shelter');
  if (p.greenbelt) amenities.push('Greenbelt access');
  if (p.fishing) amenities.push('Fishing');
  if (p.dogPark) amenities.push('Dog off-leash area');
  if (p.openPlay) amenities.push('Open play areas');
  amenities.push(...p.courts.map(cap), ...p.fields.map(cap), ...p.extras.map(cap));

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Park',
    name: p.name,
    url,
    address: { '@type': 'PostalAddress', streetAddress: p.address, addressLocality: 'Boise', addressRegion: 'ID', postalCode: p.zip, addressCountry: 'US' },
    geo: { '@type': 'GeoCoordinates', latitude: p.lat, longitude: p.lon },
    description: descText.replace(/\s+/g, ' ').slice(0, 300),
    amenityFeature: amenities.map(a => ({ '@type': 'LocationFeatureSpecification', name: a, value: true })),
    isAccessibleForFree: true,
    ...(p.photo ? { image: SITE + p.photo.file } : {}),
  };
  const breadcrumb = {
    '@context': 'https://schema.org', '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Boise Parks', item: SITE + '/' },
      { '@type': 'ListItem', position: 2, name: p.name, item: url },
    ],
  };

  const factRows = [
    ['Size', `${p.acres} acres`],
    ['Area', p.area],
    ['Type', p.type + ' park'],
    ['Address', `${p.address}, Boise, ID ${p.zip}`],
    ['Restrooms', RESTROOM_LABEL[p.restroom]],
    ...(p.parking ? [['Parking', parkingText(p)]] : []),
    ['Shade', SHADE_LABEL[p.shade] + (p.trees ? ` (${p.trees.toLocaleString()} park trees in the city inventory)` : '')],
  ];
  if (p.water) factRows.push(['Water play', `${p.water.type} — ${p.water.hours}`]);
  if (p.reservable) factRows.push(['Reservations', 'Picnic shelter/area reservable through the city']);

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  ${gaSnippet}
  <title>${esc(title)}</title>
  <meta name="description" content="${metaDesc}">
  <link rel="canonical" href="${url}">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${metaDesc}">
  <meta property="og:type" content="place">
  <meta property="og:url" content="${url}">
  <meta property="og:image" content="${p.photo ? SITE + p.photo.file : SITE + '/og-image.png'}">
  ${p.photo ? '' : '<meta property="og:image:width" content="1200"><meta property="og:image:height" content="630">'}
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${metaDesc}">
  <meta name="twitter:image" content="${p.photo ? SITE + p.photo.file : SITE + '/og-image.png'}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600..800&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
  <link rel="stylesheet" href="/styles.css">
  <script type="application/ld+json">${JSON.stringify(schema)}</script>
  <script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>
</head>
<body class="bg-cream font-sans text-ink">
${header}
<main class="mx-auto max-w-4xl px-4 pb-8 pt-8">
  <nav class="text-[13px] text-bark" aria-label="Breadcrumb"><a href="/" class="hover:text-meadow-deep">Boise Parks</a> <span class="mx-1 text-bark/50">/</span> <span class="font-medium text-meadow-deep">${esc(p.name)}</span></nav>
  <h1 class="mt-3 font-display text-3xl font-bold text-meadow-deep sm:text-4xl">${esc(p.name)}</h1>
  <p class="mt-1.5 text-[15px] text-bark"><a href="${mapsUrl(p)}" rel="noopener" class="underline decoration-meadow/40 underline-offset-2 hover:text-meadow-deep">${esc(p.address)}, Boise, ID ${esc(p.zip)}</a> · ${p.acres} acres · ${esc(p.area)}</p>

  ${p.photo ? `<figure class="mt-6">
    <img src="${esc(p.photo.file)}" alt="${esc(p.name)} in Boise, Idaho" class="aspect-[16/8] w-full rounded-2xl object-cover shadow-card" loading="lazy">
    <figcaption class="mt-1.5 text-[11.5px] text-bark">Photo: <a href="${esc(p.photo.source)}" rel="noopener" class="underline hover:text-meadow-deep">${esc(p.photo.author)}</a> · <a href="${esc(p.photo.licenseUrl)}" rel="noopener" class="underline hover:text-meadow-deep">${esc(p.photo.license)}</a> via Wikimedia Commons</figcaption>
  </figure>` : ''}

  ${p.tip ? `<div class="mt-6 rounded-2xl border border-sun/40 bg-sun-light px-5 py-4"><p class="text-[13px] font-bold uppercase tracking-wide text-sun">Parent notes</p><p class="mt-1.5 text-[15px] leading-relaxed">${esc(p.tip)}</p></div>` : ''}

  <div class="mt-8 grid gap-8 sm:grid-cols-5">
    <div class="sm:col-span-3">
      <h2 class="font-display text-xl font-bold text-meadow-deep">The essentials</h2>
      <dl class="mt-3 divide-y divide-meadow/10 rounded-2xl border border-meadow/15 bg-white px-5 shadow-card">
        ${factRows.map(([k, v]) => `<div class="flex gap-4 py-3 text-[14.5px]"><dt class="w-28 shrink-0 font-semibold text-meadow-deep">${esc(k)}</dt><dd class="text-ink/90">${esc(v)}</dd></div>`).join('\n        ')}
      </dl>
      ${pgBits ? `
      <h2 class="mt-8 font-display text-xl font-bold text-meadow-deep">Playground</h2>
      <ul class="mt-3 space-y-2 rounded-2xl border border-meadow/15 bg-white px-5 py-4 text-[14.5px] shadow-card">
        ${pgBits.map(b => `<li class="flex gap-2"><span class="text-meadow">✓</span> ${esc(b)}</li>`).join('\n        ')}
      </ul>` : `<p class="mt-8 rounded-2xl border border-meadow/15 bg-white px-5 py-4 text-[14.5px] text-bark shadow-card">No playground at this park.</p>`}
      ${p.cityUrl ? `
      <p class="mt-8 text-[13px] text-bark">For the city's official write-up and any current alerts, see the <a href="${esc(p.cityUrl)}" class="underline hover:text-meadow-deep" rel="noopener">${esc(p.name)} page at Boise Parks and Recreation</a>.</p>` : ''}
    </div>
    <aside class="sm:col-span-2">
      <div class="mb-4 overflow-hidden rounded-2xl border border-meadow/15 bg-white shadow-card">
        <div id="locmap" class="h-48 w-full"></div>
        <p class="px-5 py-3 text-[13px] leading-snug"><span aria-hidden="true">📍 </span><a href="${mapsUrl(p)}" rel="noopener" class="underline hover:text-meadow-deep">${esc(p.address)}, Boise, ID ${esc(p.zip)}</a> <span class="text-bark">— view on Google Maps</span></p>
      </div>
      <div class="mb-4 rounded-2xl border border-meadow/15 bg-white p-5 shadow-card">
        <div class="flex items-center justify-between gap-3">
          <h2 class="font-display text-lg font-bold text-meadow-deep">Parent Score</h2>
          <span class="rounded-xl px-2.5 py-1 text-lg font-bold ${scoreClasses(p.score)}">${fmtScore(p.score)}<span class="text-[12px] font-semibold opacity-70">/10</span></span>
        </div>
        <ul class="mt-3 space-y-1.5 text-[13px] text-ink/85">
          ${p.scoreRows.map(r => `<li class="flex items-baseline justify-between gap-2"><span>${esc(r.label)}</span><span class="font-semibold ${r.got === 0 ? 'text-bark/50' : 'text-meadow-deep'}">${fmtScore(r.got)}<span class="font-normal text-bark/60">/${fmtScore(r.max)}</span></span></li>`).join('\n          ')}
          <li class="flex items-baseline justify-between gap-2 border-t border-meadow/10 pt-1.5"><span>Bonus features${p.bonus.items.length ? ` <span class="text-bark/60">(${esc(p.bonus.items.join(', '))})</span>` : ''}</span><span class="font-semibold ${p.bonus.got === 0 ? 'text-bark/50' : 'text-meadow-deep'}">+${fmtScore(p.bonus.got)}<span class="font-normal text-bark/60">/1</span></span></li>
        </ul>
        <p class="mt-3 text-[12px] leading-snug text-bark">How good a visit is with kids — playground, tree cover and grass count most; water, shelters and trails are bonuses; parking never counts against a park. <a href="/#about" class="underline">Methodology</a>.</p>
      </div>
      <div class="rounded-2xl border border-meadow/15 bg-white p-5 shadow-card">
        <h2 class="font-display text-lg font-bold text-meadow-deep">Everything here</h2>
        <ul class="mt-3 flex flex-wrap gap-1.5 text-[12.5px] font-medium">
          ${amenities.map(a => `<li class="rounded-md bg-meadow-light px-2 py-1 text-meadow-deep">${esc(a)}</li>`).join('\n          ')}
        </ul>
        <div class="mt-5 grid gap-2">
          <a href="/?park=${p.slug}#map" class="rounded-xl bg-meadow px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-meadow-dark">See on the full map</a>
          ${p.cityUrl ? `<a href="${esc(p.cityUrl)}" target="_blank" rel="noopener" class="rounded-xl border border-meadow/30 bg-white px-4 py-2.5 text-center text-sm font-semibold text-meadow-deep hover:bg-meadow-light">Official city page</a>` : ''}
        </div>
      </div>
    </aside>
  </div>
</main>
${footer}
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<script>
(function(){
  var lat=${p.lat}, lon=${p.lon};
  var m=L.map('locmap',{scrollWheelZoom:false,attributionControl:true}).setView([lat,lon],15);
  L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>',maxZoom:19}).addTo(m);
  L.circleMarker([lat,lon],{radius:9,color:'#fff',weight:2,fillColor:'#2E7D32',fillOpacity:.95}).addTo(m).bindPopup(${JSON.stringify(p.name)});
})();
</script>
</body>
</html>
`;
  const dir = path.join(pgDir, p.slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html);
}

// ---------- guide pages (/splash-pads/, /restrooms/, /best-playgrounds/) ----------
const guideSlugs = buildGuides({
  ROOT, SITE, parks, esc, cap, header, footer, gaSnippet,
  RESTROOM_LABEL, SHADE_LABEL, scoreClasses, fmtScore,
});

// ---------- cache-bust the data bundle + stamp analytics into index.html ----------
const idxPath = path.join(ROOT, 'index.html');
const stamp = Date.now().toString(36);
let idxHtml = fs.readFileSync(idxPath, 'utf8')
  .replace(/js\/parks-data\.js\?v=[a-z0-9]+/, `js/parks-data.js?v=${stamp}`)
  .replace(/<!-- ga:start -->[\s\S]*?<!-- ga:end -->/, `<!-- ga:start -->\n  ${gaSnippet}\n  <!-- ga:end -->`);
fs.writeFileSync(idxPath, idxHtml);

// ---------- sitemap ----------
const today = new Date().toISOString().slice(0, 10);
const urls = [
  `${SITE}/`,
  ...guideSlugs.map(s => `${SITE}/${s}/`),
  ...parks.map(p => `${SITE}/parks/${p.slug}/`),
];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);

console.log(`✓ ${parks.length} park pages, ${guideSlugs.length} guides (${guideSlugs.join(', ')}), js/parks-data.js, sitemap.xml`);
